show news detail
AT-PHPIntership/danang_bus pull request #67
Opened 2017-04-12 17:00 UTC by at-dieule

2017-04-13 10:10 UTC, at-vienle commented
@at-dieule please commit controller also

2017-04-13 10:10 UTC, ghost requested changes

2017-04-13 10:10 UTC, at-vienle commented on config/constants.php
> +		'LIMIT_NEWS_INDEX' => '2',
no need this `const` the Eloquent have the `perPage` property, default is 15, If you want to custom, just define in the model class

2017-04-13 10:10 UTC, at-vienle commented on resources/lang/en/footer.php
> +<?php
why this file is in `en` folder, but the content is VietNamese

2017-04-13 10:10 UTC, at-vienle commented on resources/views/danabus/news/news.blade.php
> +              <h2 class="map">{{ trans('index.map')}}</h2>
I don't see the lang `index.map`

2017-04-14 03:38 UTC, ghost requested changes
Pls check my cmt

2017-04-14 03:38 UTC, at-vienle commented on app/Http/Controllers/Danabus/NewsController.php
> +        $cats = Category::all();
Why you need `$categories` in this request?

2017-04-14 03:38 UTC, at-vienle commented on app/Http/Controllers/Danabus/NewsController.php
> +        $news = News::find($id);
`findOrFail` is better

2017-04-14 03:38 UTC, at-vienle commented on config/constants.php
> +		'LIMIT_NEWS_INDEX' => '2',
pls remove

2017-04-14 03:44 UTC, at-dieule commented on app/Http/Controllers/Danabus/NewsController.php
> +        $cats = Category::all();
because on index page i will show categories and filter news

2017-04-16 15:46 UTC, closed without merging