Admin CRUD direction
AT-PHPIntership/danang_bus pull request #95
Opened 2017-04-20 16:46 UTC by at-dieule

2017-04-21 01:37 UTC, at-vienle commented
@at-dieule pls resolve conflict

2017-04-24 02:49 UTC, ghost requested changes
pls check my cmt

2017-04-24 02:49 UTC, at-vienle commented on app/Http/Controllers/Admin/DirectionController.php
> +        $direction = new Directions($request->all());
please change `Directions` model to single case

2017-04-28 02:34 UTC, dinhnhan-dtu reviewed
pls check my cmt

2017-04-28 02:34 UTC, at-dinhnhan commented on app/Http/Controllers/Admin/RouteController.php
> +            $newroute = new Route($route);
pls change $newroute to $newRoute

2017-04-28 07:15 UTC, tinhdang reviewed
@at-dieule check my cmt

2017-04-28 07:15 UTC, at-tinhdang commented on public/admin/js/main.js
> -});
why remove this ?

2017-04-28 07:15 UTC, at-tinhdang commented on routes/web.php
> +    Route::resource('/routes', 'RouteController');
use `expect`  or `only`  if you don't use all function resource

2017-04-28 07:15 UTC, at-tinhdang commented on app/Http/Controllers/Admin/RouteController.php
> +        $route = $request->only(['name','distance','frequency','frequency_peak','start_time','end_time','type']);
pls change $route to $routeRequest

2017-05-08 02:23 UTC, ghost requested changes
pls check cmt

2017-05-08 02:23 UTC, at-vienle commented on public/admin/js/main.js
> +  $('.btn_add_stop_backward').on('click', function(){
pls follow DRY rules.

2017-05-10 06:41 UTC, ghost requested changes
pls check cmt

2017-05-10 06:41 UTC, at-vienle commented on app/Http/Controllers/Admin/RouteController.php
> +        $routeRequest = $request->only(['name','distance','frequency','frequency_peak','start_time','end_time','type']);
just get all request params, no need to limit. Because you already have `fillable` in model. If you don't understand `$fillable` pls research

2017-05-10 06:41 UTC, at-vienle commented on public/admin/js/main.js
> +  $(document).on("click",".delete",function() {
`.delete` is not a good name, it's too common.

2017-05-10 07:25 UTC, ghost approved these changes
LGTM

2017-05-10 07:25 UTC, merged